apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documents
  template:
    metadata:
      labels:
        app: documents
    spec:
      containers:
      - name: documents
        image: documents-image:latest # Replace with your image name
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: documents-service
spec:
  selector:
    app: documents
  ports:
    - protocol: TCP
      port: 8000 # Port for internal communication
      targetPort: 8000
  type: ClusterIP # Only accessible within the cluster
