apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels: { app: payment }
  template:
    metadata:
      labels: { app: payment }
    spec:
      containers:
        - name: payment
          image: ghcr.io/fedorovmichael/kub_ms-payment:main
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8000 }]
          readinessProbe: { tcpSocket: { port: 8000 }, initialDelaySeconds: 3, periodSeconds: 10 }
          livenessProbe:  { tcpSocket: { port: 8000 }, initialDelaySeconds: 10, periodSeconds: 20 }
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: prod
spec:
  selector: { app: payment }
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
