name: Build & Push (services)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # needed for ghcr push

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO:  ${{ github.event.repository.name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc:
          - name: gateway
            path: ./gateway
          - name: documents
            path: ./documents
          - name: payment
            path: ./payment

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER }}/${{ env.REPO }}-${{ matrix.svc.name }}
          tags: |
            type=ref,event=branch
            type=sha
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build & Push ${{ matrix.svc.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER }}/${{ env.REPO }}-${{ matrix.svc.name }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER }}/${{ env.REPO }}-${{ matrix.svc.name }}:buildcache,mode=max
